name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Bun
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest  # Installs the latest stable version of Bun

      # Step 3: Install dependencies
      - name: Install dependencies
        run: bun install

      # Step 4: Build and export the Next.js app
      - name: Build and export Next.js app
        run: |
          bun run build

      # Step 5: Configure GitHub Pages deployment
      - name: Configure Pages
        uses: actions/configure-pages@v3

      # Step 6: Upload built artifacts
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './out' # Path to the exported files

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2